CREATE TABLE [dbo].[AppUser]
(
	[UserId] INT IDENTITY (1, 1) NOT NULL,
	[FullName] NVARCHAR(200) NOT NULL,
	[Username] NVARCHAR(100) NOT NULL,
	[Role] INT NOT NULL,
	[IsDeleted] BIT NOT NULL DEFAULT (0),
	CONSTRAINT [PK_User] PRIMARY KEY NONCLUSTERED ([UserId] ASC)
)
